apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: env-injector-mw.cerit.io
  annotations:
    cert-manager.io/inject-ca-from-secret: env-injector/env-injector-mw-cert-secret
webhooks:
  - name: env-injector-mw.cerit.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 10
    clientConfig:
      service:
        name: env-injector-mw-svc
        namespace: env-injector
        path: "/mutate"
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "*"
