apiVersion: v1
kind: ServiceAccount
metadata:
  name: env-injector-sa
  namespace: env-injector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: env-injector-role
rules:
  - apiGroups: [""]
    resources: ["pods"] # PODS/STATUS
    verbs: ["get", "watch", "list", "patch", "create"]
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: env-injector-pods-rb
subjects:
  - kind: ServiceAccount
    name: env-injector-sa
    namespace: env-injector
roleRef:
  kind: ClusterRole
  name: env-injector-role
  apiGroup: rbac.authorization.k8s.io
