apiVersion: v1
kind: Service
metadata:
  name: env-injector-mw-svc
  namespace: env-injector
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: env-injector-webhook